Fix bug with uniform score
embeddings-benchmark/mteb pull request #1189
Opened 2024-09-01 10:15 UTC by AlexeyVatolin

## Checklist

- [ ] Run tests locally to make sure nothing is broken using `make test`. 
- [ ] Run the formatter to format the code using `make lint`. 

### Adding datasets checklist

**Reason for dataset addition**: ... 

- [ ] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
  - [ ] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [ ] `intfloat/multilingual-e5-small`
- [ ] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [ ] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [ ] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [ ] Run tests locally to make sure nothing is broken using `make test`. 
- [ ] Run the formatter to format the code using `make lint`. 

### Adding a model checklist

 - [ ] I have filled out the ModelMeta object to the extent possible
 - [ ] I have ensured that my model can be loaded using
   - [ ] `mteb.get_model(model_name, revision_id)` and
   - [ ] `mteb.get_model_meta(model_name, revision_id)`
 - [ ] I have tested the implementation works on a representative set of tasks.

2024-09-01 19:09 UTC, KennethEnevoldsen requested changes

2024-09-01 19:09 UTC, KennethEnevoldsen commented on mteb/tasks/Classification/zho/CMTEBClassification.py
I merged this in #1190 based on your comment in the issue before I saw this PR.

2024-09-01 19:09 UTC, KennethEnevoldsen commented on mteb/tasks/Classification/eng/LegalBenchClassification.py
> -class Diversity1LegalBenchClassification(AbsTaskClassification):
I don't think we should remove these. Though I agree that they are very challenging tasks (and potentially problematically so).

2024-09-01 21:43 UTC, AlexeyVatolin commented on mteb/tasks/Classification/zho/CMTEBClassification.py
I forgot to link this pull request to issue. I remove the changes and leave only the update of the Contributors table. Please update it in the article too

2024-09-02 10:56 UTC, KennethEnevoldsen commented on mteb/tasks/Classification/zho/CMTEBClassification.py
Will update the article as well once we have the last contributors in (but have a script for it so if you are in the table and have more than 10 points you should get in)

2024-09-02 10:57 UTC, KennethEnevoldsen approved these changes

2024-09-02 10:57 UTC, merged

2024-09-02 12:15 UTC, AlexeyVatolin commented on mteb/tasks/Classification/zho/CMTEBClassification.py
Yeah, I've got more than 10 points

2024-09-03 12:30 UTC, KennethEnevoldsen commented on mteb/tasks/Classification/zho/CMTEBClassification.py
Just to make sure I reran the author list code in this [PR](https://github.com/embeddings-benchmark/mteb/pull/1194) and manually checked that your name appear on the author list.