Added Hindi sentiment analysis dataset
embeddings-benchmark/mteb pull request #491
Opened 2024-04-22 18:43 UTC by Akash190104

Sentiment Analysis Dataset for hindi. Read the sentences to realize it consists of reviews. 

## Checklist for adding MMTEB dataset

Reason for dataset addition:

Covers sentiment Analysis in Hindi which was not covered before.

- [x] I have tested that the dataset runs with the `mteb` package.
- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb run -m {model_name} -t {task_name}` command.
  - [x] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [x] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] I have considered the size of the dataset and reduced it if it is too big (2048 examples is typically large enough for most tasks)
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 
- [ ] I have added points for my submission to the [points folder](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md) using the PR number as the filename (e.g. `438.jsonl`).

2024-04-22 20:20 UTC, isaac-chung requested changes
Thanks for your contribution! Just a few comments.
Feel free to add 2 points for the datasets and 2 points to me for the review.

2024-04-22 20:20 UTC, isaac-chung commented on mteb/tasks/Classification/hin/SentimentAnalysisHindi.py
> +        bibtex_citation=None,
Maybe
```
@misc{OdiaGenAI,
  author = {Shantipriya Parida and Sambit Sekhar and Soumendra Kumar Sahoo and Swateek Jena and Abhijeet Parida and Satya Ranjan Dash and Guneet Singh Kohli},
  title = {OdiaGenAI: Generative AI and LLM Initiative for the Odia Language},
  year = {2023},
  publisher = {Hugging Face},
  journal = {Hugging Face repository},
  howpublished = {\url{https://huggingface.co/OdiaGenAI}},
}
```

2024-04-22 20:20 UTC, isaac-chung commented on mteb/tasks/Classification/hin/SentimentAnalysisHindi.py
> +        license=None,
```suggestion
        license="CC BY-NC-SA 4.0",
```

2024-04-22 20:20 UTC, isaac-chung commented on mteb/tasks/Classification/hin/SentimentAnalysisHindi.py
> +        date=None,
Rough estimate based on versions?

2024-04-22 20:20 UTC, isaac-chung commented on mteb/tasks/Classification/hin/SentimentAnalysisHindi.py
> +        socioeconomic_status=None,
```suggestion
        socioeconomic_status="mixed",
```

2024-04-22 20:20 UTC, isaac-chung commented on mteb/tasks/Classification/hin/SentimentAnalysisHindi.py
> +        text_creation=None,
```suggestion
        text_creation="found",
```

2024-04-22 20:20 UTC, isaac-chung commented on mteb/tasks/Classification/hin/SentimentAnalysisHindi.py
> +        annotations_creators=None,
```suggestion
        annotations_creators="derived",
```

2024-04-23 16:01 UTC, Akash190104 commented
Added changes. Please take a look @isaac-chung. Thanks!

2024-04-23 17:10 UTC, isaac-chung reviewed
Sorry I missed it the first round. Could you please also add the results from running `mteb run -m {model_name} -t {task_name}` with the models listed in the PR checklist? 

Otherwise it looks good. Thanks again!

2024-04-23 21:58 UTC, Akash190104 commented
I didn't lint properly the first time. Could you please enable auto-merge again.
Sorry for the inconvenience.

2024-04-24 07:11 UTC, merged