Added Kannada News Classification Dataset
embeddings-benchmark/mteb pull request #492
Opened 2024-04-22 20:17 UTC by Akash190104

Added Kannada News Classification Dataset. 
## Checklist for adding MMTEB dataset

Reason for dataset addition:

This is the first classification task for Kannada.

- [x] I have tested that the dataset runs with the `mteb` package.
- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb run -m {model_name} -t {task_name}` command.
  - [x] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [x] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] I have considered the size of the dataset and reduced it if it is too big (2048 examples is typically large enough for most tasks)
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 
- [ ] I have added points for my submission to the [points folder](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md) using the PR number as the filename (e.g. `438.jsonl`).

2024-04-22 20:44 UTC, isaac-chung requested changes
Thanks for adding this! Just a few comments.
Feel free to add 2 points for the dataset and 2 points to me for the review.

2024-04-22 20:44 UTC, isaac-chung commented on mteb/tasks/Classification/kan/Kannada_News_Classification.py
> +        n_samples={"train": 6460},
Could define a var N_SAMPLES=2048 and use it below as well.

2024-04-22 20:44 UTC, isaac-chung commented on mteb/tasks/Classification/kan/Kannada_News_Classification.py
> +        dialect=None,
```suggestion
        dialect=[],
```

2024-04-22 20:44 UTC, isaac-chung commented on mteb/tasks/Classification/kan/Kannada_News_Classification.py
> +        annotations_creators=None,
Could you please fill these out based on https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object?

2024-04-22 20:51 UTC, Akash190104 commented
@isaac-chung Thank you for your suggestions. I would make the changes, ina few hours. Just to clarify, based on this, https://github.com/embeddings-benchmark/mteb/tree/main/docs/mmteb am I eligible for the bonus here?
It's okay either way. Just wanted to understand the system. Thanks!

2024-04-22 20:56 UTC, isaac-chung commented
Yep, you will be. Follow the last point on the PR checklist to add a file to the points folder.

2024-04-23 16:35 UTC, Akash190104 commented
Made changes.

2024-04-24 07:11 UTC, isaac-chung approved these changes
Thanks for adding this! FYI kan is covered by `IndicSentimentClassification`, so this dataset would yield 2 points instead of 6.

2024-04-24 07:13 UTC, merged