swiss judgement classification dataset
embeddings-benchmark/mteb pull request #569
Opened 2024-04-25 08:22 UTC by Akash190104

Solves issue #542 

Added the swiss judgement classification dataset. Let me know, if anything needs to be added.
## Checklist for adding MMTEB dataset

Reason for dataset addition:

- [x] I have tested that the dataset runs with the `mteb` package.
- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb run -m {model_name} -t {task_name}` command.
  - [x] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [x] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 
- [ ] I have added points for my submission to the [points folder](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md) using the PR number as the filename (e.g. `438.jsonl`).

2024-04-25 08:44 UTC, Akash190104 commented
ran into a linting issue for a different multihateclassification file.
Would really appreciate the conflict to be resolved.

2024-04-25 10:03 UTC, KennethEnevoldsen reviewed
Looks good, a few comments which should be quick to address

Please add points as well

2024-04-25 10:03 UTC, KennethEnevoldsen commented on mteb/tasks/Classification/multilingual/SwissJudgementClassification.py
> +        dialect=None,
```suggestion
        dialect=[],
```

2024-04-25 10:03 UTC, KennethEnevoldsen commented on mteb/tasks/Classification/multilingual/SwissJudgementClassification.py
> +        n_samples={"train": 59709, "validation": 8208, "test": 17357},
```suggestion
        n_samples={"test": 17357},
```

2024-04-26 18:40 UTC, Akash190104 commented
@KennethEnevoldsen, I have fixed things up based on your reviews. Please let me know if any more changes are necessary.

2024-04-29 08:27 UTC, KennethEnevoldsen requested changes

2024-04-29 08:27 UTC, KennethEnevoldsen commented
@Akash190104 seems like there still are a few issues with the subsampling

2024-05-04 20:39 UTC, Akash190104 commented
I made changes based on the review comments.
kept the ```n_samples={"test": 17357}```  but downsampled it later using ```stratified_subsampling```.

Received this error when choosing 2048 sentences:
```ValueError: test_size=2048 should be either positive and smaller than the number of samples 812 or a float in the (0, 1) range```
So went with 2046 samples for 'de' and 'fr' and 810 samples for 'ita'. Hope that isn't a problem. Incase that is, would love to understand how to fix it. Thanks

2024-05-06 16:43 UTC, Akash190104 commented
Could you please look into this @KennethEnevoldsen ?
I feel this is good to go now.

2024-05-08 19:30 UTC, KennethEnevoldsen approved these changes

2024-05-08 19:30 UTC, KennethEnevoldsen commented on mteb/tasks/Classification/multilingual/SwissJudgementClassification.py
> +        n_samples={"test": 17357},
```suggestion
        n_samples={"test": 2048},
```

2024-05-08 19:33 UTC, KennethEnevoldsen commented
Thanks for the ping @Akash190104, sorry for the late response. I have fixed a minor issue and enabled automerge

2024-05-08 19:43 UTC, merged